[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_port = COM14
monitor_port = COM14
lib_deps =
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit AS7343
  adafruit/Adafruit BusIO
